# Generated by Django 2.2.19 on 2023-01-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230119_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
    ]
